books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:books_id>/', views.detail, name='detail'),
    path('list/<int:type_id>/<int:page>/', views.list, name='list'),
]

ebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('books.urls', namespace='books')),
    path('order/', include('order.urls', namespace='order')),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('order/', views.place, name='place'),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls import *

from .views import textareas_js, spell_check, flatpages_link_list, compressor, filebrowser, preview
urlpatterns = [
    url(r'^js/textareas/(?P<name>.+)/$', textareas_js, name='textareas_js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', textareas_js, name='textareas_js'),
    url(r'^spellchecker/$', spell_check, name='spell_check'),
    url(r'^flatpages_link_list/$', flatpages_link_list, name='flatpages_link_list'),
    url(r'^compressor/$', compressor, name='compressor'),
    url(r'^filebrowser/$', filebrowser, name='filebrowser'),
    url(r'^preview/(?P<name>.+)/$', preview, name='preview'),
]

users/urls.py
from . import views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register_handle/', views.register_handle, name='register_handle'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', views.user, name='user'),
]

order/db/users/models.py
from django.db import models
from .base_model import BaseModel
from ...utils.get_hash import get_hash

# Create your models here.
class PassportManager(models.Manager):
    def add_one_passport(self, username, password, email):
        passport = self.create(username=username, password=get_hash(password), email=email)
        return passport

    def get_one_passport(self, username, password):
        try:
            passport = self.get(username=username, password=get_hash(password))
        except self.model.DoesNotExist:
            passport = None
        return passport

class Passport(BaseModel):
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名称')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')

    objects = PassportManager()

    class Meta:
        db_table = 'user_account'

class AddressManager(models.Manager):
    def get_default_address(self, passport_id):
        try:
            addr = self.get(passport_id=passport_id, is_default=True)
        except self.model.DoesNotExist:
            addr = None

        return addr

    def add_one_address(self, recipient_name, recipient_addr, zip_code, recipient_phone, passport_id):
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            is_default = False
        else:
            is_default = True

        addr = self.create(passport_id=passport_id, recipient_name=recipient_name, recipient_addr=recipient_addr, zip_code=zip_code, recipient_phone=recipient_phone, is_default=is_default)

        return addr


class Address(BaseModel):
    recipient_name = models.CharField(max_length=20, verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')
    passport = models.ForeignKey(Passport, verbose_name='我的账户', on_delete=models.CASCADE)

    objects = AddressManager()

    class Meta:
        db_table = 'user_address'

users/models.py
from django.db import models
from .db.base_model import BaseModel
from .utils.get_hash import get_hash

# Create your models here.
class PassportManager(models.Manager):
    def add_one_passport(self, username, password, email):
        passport = self.create(username=username, password=get_hash(password), email=email)
        return passport

    def get_one_passport(self, username, password):
        try:
            passport = self.get(username=username, password=get_hash(password))
        except self.model.DoesNotExist:
            passport = None
        return passport

class Passport(BaseModel):
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名称')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')

    objects = PassportManager()

    class Meta:
        db_table = 'user_account'

class AddressManager(models.Manager):
    def get_default_address(self, passport_id):
        try:
            addr = self.get(passport_id=passport_id, is_default=True)
        except self.model.DoesNotExist:
            addr = None

        return addr

    def add_one_address(self, recipient_name, recipient_addr, zip_code, recipient_phone, passport_id):
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            is_default = False
        else:
            is_default = True

        addr = self.create(passport_id=passport_id, recipient_name=recipient_name, recipient_addr=recipient_addr, zip_code=zip_code, recipient_phone=recipient_phone, is_default=is_default)

        return addr


class Address(BaseModel):
    recipient_name = models.CharField(max_length=20, verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')
    passport = models.ForeignKey(Passport, verbose_name='我的账户', on_delete=models.CASCADE)

    objects = AddressManager()

    class Meta:
        db_table = 'user_address'

users/forms.py
from django import forms
from .models import Passport, Address

class PassportForm(forms.ModelForm):
    class Meta:
        model = Passport
        fields = ['username', 'password', 'email', 'is_active']
        labels = {'username': 'username', 'password': 'password', 'email': 'email', 'is_active': 'is_active'}

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['recipient_name', 'recipient_addr', 'zip_code', 'recipient_phone', 'is_default']
        labels = {'recipient_name': '', 'recipient_addr': '',  'zip_code': '', 'recipient_phone': '', 'is_default': ''}

users/views.py
from django.shortcuts import render, get_object_or_404, reverse
import re
from .models import Passport, Address
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
<<<<<<< HEAD
=======
from .forms import PassportForm, AddressForm
>>>>>>> 0f7df8ea13f4abb0a17df9f38f541005dcd958e2

# Create your views here.
def register(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    passport = Passport.objects.get_one_passport(username=username, password=password)

    request.session['username'] = username
<<<<<<< HEAD
    request.session['passport_id'] = passport.id
=======
    if passport:
        request.session['passport_id'] = passport.id
>>>>>>> 0f7df8ea13f4abb0a17df9f38f541005dcd958e2

    return render(request, 'users/register.html')

def register_handle(request):
    username = request.POST.get('user_name')
    password = request.POST.get('pwd')
    email = request.POST.get('email')

    if not all([username, password, email]):
        context = {'errormsg': '参数不能为空! '}
        return render(request, 'users/register.html', context)

    if not re.match(r'^[A-Za-z0-9][\w\.\-]*@[a-z0-9]+(\.[a-z]{2,5}){1,2}$', email):
        context = {'errormsg': '邮箱不合法! '}
        return render(request, 'users/register.html', context)

    try:
        Passport.objects.add_one_passport(username=username, password=password, email=email)
    except:
        context = {'errormsg': '用户名已存在! '}
        return render(request, 'users/register.html', context)

    return HttpResponseRedirect(reverse('books:index'))

def logout_view(request):
    logout(request)
    request.session.flush()
    return HttpResponseRedirect(reverse('books:index'))

<<<<<<< HEAD
@login_required
def user(request):
    passport_id = request.session.get('passport_id')

    addr =Address.objects.get_default_address(passport_id=passport_id)
=======
def user(request):
    passport_id = request.session.get('passport_id')

    addr = Address.objects.get_default_address(passport_id=passport_id)
>>>>>>> 0f7df8ea13f4abb0a17df9f38f541005dcd958e2

    books_list = []
    context = {
        'addr': addr, 'page': 'user', 'books_list': books_list
    }

    return render(request, 'users/info.html', context)

<<<<<<< HEAD
=======
def login(request):
    form = PassportForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)

>>>>>>> 0f7df8ea13f4abb0a17df9f38f541005dcd958e2

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    </head>

    <body>
        <div >
            <div >
                <div > 欢迎来到E-Book !</div>
                <div >
                    {% if request.session.islogin %}
                        <div style="text-align:right">
                            欢迎你: <em>{{request.session.username }}</em>
                            <span> | </span>
                            <a href="{% url 'users:login' %}"> 注销 </a>
                        </div>
                    {% else %}
                        <div style="text-align:right">
                            <a href="{% url 'users:login' %}"> 登录 </a>
                            <span> | </span>
                            <a href="{% url 'users:register' %}"> 注册 </a>
                        </div>
                    {% endif %}
                        <div style="text-align:right">
                            <span> | </span>
                            <a href="{% url 'users:user' %}"> 用户中心 </a>
                            <span> | </span>

                            <span> | </span>
                            <a href="{% url 'order:place' %}"> 我的订单 </a>
                        </div>
                </div>
            </div>
        </div>

    {# 网页顶部搜索栏 #}
        <div >
            <a href="{% url 'books:index' %}"><img src="{% static '/books/images/logo.png' %}" style="width: 160px; height:130px;" alt="E-Book's Logo"/></a>
            <div >
                <form method="get" action="/search/">
                    <input type="text" name="q" placeholder="搜索商品">
                    <input type="submit" name="" value="搜索">
                </form>
            </div>

<<<<<<< HEAD
            <div class="guest_cart fr">

                <div class="book_count fl" id="show_count">0</div>
=======
            <div >

                <!-- <div class="book_count fl" id="show_count">0</div> -->
>>>>>>> 0f7df8ea13f4abb0a17df9f38f541005dcd958e2
            </div>
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>

users/templates/users/info.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
<div>
    <h3> 用户中心 </h3>
    <ul>
        <li><a href="{% url 'users:user' %}" class="active"> 个人信息 </a></li>
        <li><a href="{% url 'users:order' %}"> 全部订单 </a></li>
        <li><a href="{% url 'users:address' %}">收货地址 </a></li>
    </ul>
</div>

<div>
    <h3> 基本信息 </h3>
    <ul>
        <li><span> 用户名：</span>{{ request.session.username }}</li>
        {% if addr %}
            <li><span> 联系方式：</span>{{ addr.recipient_phone }}</li>
            <li><span> 联系地址：</span>{{ addr.recipient_addr }}</li>
        {% else %}
             <li><span> 联系方式：</span>无</li>
             <li><span> 联系地址：</span>无</li>
        {% endif %}
    </ul>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block header %}
    <h2> 登录你的账户 </h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit" class="btn"> 登录 </button>

        <input type="hidden" name="next" value="{% url 'books:index' %}"/>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %} E-Book-注册 {% endblock title %}
{% block topfiles%}
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block content %}
    <div class="register_con">
        <div class="l_con fl">
            <!-- <a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;" alt="E-Book's Logo"/></a> -->
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1> 用户注册 </h1>
                <a href="#">登录 </a>
            </div>

            <div class="reg_form clearfix">
                <form method="post" action="{url 'users:register_handle'}" >
                {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名：</label>
                            <input type="text" name="username" id="username">
                            <span class="error_tips"> 提示信息 </span>
                        </li>

                        <li>
                            <label> 密码：</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tips"> 提示信息 </span>
                        </li>

                        <li>
                            <label> 确认密码：</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tips"> 提示信息 </span>
                        </li>

                        <li>
                            <label> 邮箱：</label>
                            <input type="email" name="email" id="email">
                            <span class="error_tips"> 提示信息 </span>
                        </li>

                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label> 同意使用协议 </label>
                            <span class="error_tips2"> 提示信息 </span>
                        </li>

                        <li class="reg_sub">
                            <input type="submit" value="注册" name="">
                            {{errormsg}}
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block cart_count %}{% endblock cart_count%}