books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:books_id>/', views.detail, name='detail'),
    path('list/<int:type_id>/<int:page>/', views.list, name='list'),
]

ebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('books.urls', namespace='books')),
    path('order/', include('order.urls', namespace='order')),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('order/', views.place, name='place'),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls import *

from .views import textareas_js, spell_check, flatpages_link_list, compressor, filebrowser, preview
urlpatterns = [
    url(r'^js/textareas/(?P<name>.+)/$', textareas_js, name='textareas_js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', textareas_js, name='textareas_js'),
    url(r'^spellchecker/$', spell_check, name='spell_check'),
    url(r'^flatpages_link_list/$', flatpages_link_list, name='flatpages_link_list'),
    url(r'^compressor/$', compressor, name='compressor'),
    url(r'^filebrowser/$', filebrowser, name='filebrowser'),
    url(r'^preview/(?P<name>.+)/$', preview, name='preview'),
]

users/urls.py
from . import views
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register_handle/', views.register_handle, name='register_handle'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user/', views.user, name='user'),
]

books/models.py
from django.db import models
from .db.base_model import BaseModel
from tinymce.models import HTMLField
from .enums import *

# Create your models here.

class BooksManager(models.Manager):
    def get_books_by_type(self, type_id, limit=None, sort='default'):
        if sort == 'new':
            order_by = ('-create_time', )
        elif sort == 'hot':
            order_by = ('-sales', )
        elif sort == 'price':
            order_by = ('price', )
        else:
            order_by = ('-pk', )

        books_query = self.filter(type_id=type_id).order_by(*order_by)

        if limit:
            books_query = books_query[:limit]
        return books_query

    def get_books_by_id(self, books_id):
        try:
            books = self.get(id=books_id)
        except self.model.DoesNotExist:
            books = None
        return books

class Books(BaseModel):
    books_type_choices = ((k, v) for k, v in BOOKS_TYPE.items())
    status_choices = ((k, v) for k, v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    description = models.CharField(max_length=128, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unit = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

    objects = BooksManager()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'books'
        verbose_name = '图书'
        verbose_name_plural = '图书'

order/db/books/models.py
from django.db import models
from .base_model import BaseModel
from tinymce.models import HTMLField
from .enums import *

# Create your models here.

class BooksManager(models.Manager):
    def get_books_by_type(self, type_id, limit=None, sort='default'):
        if sort == 'new':
            order_by = ('-create_time', )
        elif sort == 'hot':
            order_by = ('-sales', )
        elif sort == 'price':
            order_by = ('price', )
        else:
            order_by = ('-pk', )

        books_query = self.filter(type_id=type_id).order_by(*order_by)

        if limit:
            books_query = books_query[:limit]
        return books_query

    def get_books_by_id(self, books_id):
        try:
            books = self.get(id=books_id)
        except self.model.DoesNotExist:
            books = None
        return books

class Books(BaseModel):
    books_type_choices = ((k, v) for k, v in BOOKS_TYPE.items())
    status_choices = ((k, v) for k, v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    description = models.CharField(max_length=128, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unit = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

    objects = BooksManager()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'books'
        verbose_name = '图书'
        verbose_name_plural = '图书'

books/views.py
from django.shortcuts import render
from .models import Books
from .enums import *
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    python_new = Books.objects.get_books_by_type(PYTHON, limit=3, sort='new')
    python_hot = Books.objects.get_books_by_type(PYTHON, limit=4, sort='hot')
    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT, limit=3, sort='new')
    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT, limit=4, sort='hot')
    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS, limit=3, sort='new')
    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS, limit=4, sort='hot')
    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING, limit=3, sort='new')
    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING, limit=4, sort='hot')
    operationsystem_new = Books.objects.get_books_by_type(OPERATIONSYSTEM, limit=3, sort='new')
    operationsystem_hot = Books.objects.get_books_by_type(OPERATIONSYSTEM, limit=4, sort='hot')
    database_new = Books.objects.get_books_by_type(DATABASE, limit=3, sort='new')
    database_hot = Books.objects.get_books_by_type(DATABASE, limit=4, sort='hot')

    context = {
        'python_new': python_new,
        'python_hot': python_hot,
        'javascript_new': javascript_new,
        'javascript_hot': javascript_hot,
        'algorithms_new': algorithms_new,
        'algorithms_hot ': algorithms_hot ,
        'machinelearning_new': machinelearning_new,
        'machinelearning_hot': machinelearning_hot,
        'operationsystem_new': operationsystem_new,
        'operationsystem_hot': operationsystem_hot,
        'database_new': database_new,
        'database_hot': database_hot,
    }

    return render(request, 'books/index.html', context)

@login_required
def detail(request, books_id):
    books = Books.objects.get_books_by_id(books_id=books_id)

    if books is None:
        return HttpResponseRedirect(reverse('books:index'))

    books_list = Books.objects.get_books_by_type(type_id=books.type_id, limit=2, sort='new')
    type_title = BOOKS_TYPE[books.type_id]

    context = {'books': books, 'books_list': books_list, 'type_title': type_title}
    return render(request, 'books/detail.html', context)

@login_required
def list(request, type_id, page):
    sort = request.GET.get('sort', 'default')

    if type_id not in BOOKS_TYPE.keys():
        return HttpResponseRedirect(reverse('books:index'))

    books_list = Books.objects.get_books_by_type(type_id=type_id, sort=sort)

    paginator = Paginator(books_list, 1)              # 每页一条信息
    num_pages = paginator.num_pages                # 可以分成的页数

    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)

    books_list = paginator.page(page)                # 取第page分页

    if num_pages < 5:
        pages = range(1, num_pages+1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages-4, num_pages+1)
    else:
        pages = range(page-2, page+3)

    books_new = Books.objects.get_books_by_type(type_id=type_id, limit=2, sort='new')

    type_title = BOOKS_TYPE[int(type_id)]

    context = {'books_list': books_list, 'books_new': books_new, 'type_id': type_id, 'sort': sort, 'type_title': type_title, 'pages': pages}
    return render(request, 'books/list.html', context)

books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    </head>

    <body>
        <div >
            <div >
                <div > 欢迎来到E-Book !</div>
                <div >
                    {% if request.session.islogin %}
                        <div style="text-align:right">
                            欢迎你: <em>{{request.session.username }}</em>
                            <span> | </span>
                            <a href="{% url 'users:login' %}"> 注销 </a>
                        </div>
                    {% else %}
                        <div style="text-align:right">
                            <a href="{% url 'users:login' %}"> 登录 </a>
                            <span> | </span>
                            <a href="{% url 'users:register' %}"> 注册 </a>
                        </div>
                    {% endif %}
                        <div style="text-align:right">
                            <span> | </span>
                            <a href="{% url 'users:user' %}"> 用户中心 </a>
                            <span> | </span>

                            <span> | </span>
                            <a href="{% url 'order:place' %}"> 我的订单 </a>
                        </div>
                </div>
            </div>
        </div>

    {# 网页顶部搜索栏 #}
        <div >
            <a href="{% url 'books:index' %}"><img src="{% static '/books/images/logo.png' %}" style="width: 160px; height:130px;" alt="E-Book's Logo"/></a>
            <div >
                <form method="get" action="/search/">
                    <input type="text" name="q" placeholder="搜索商品">
                    <input type="submit" name="" value="搜索">
                </form>
            </div>

            <div >

                <!-- <div class="book_count fl" id="show_count">0</div> -->
            </div>
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>

books/templates/books/detail.html
{% extends 'books/base.html' %}
{% load static %}
{% block title %} E-Book-商品详情 {% endblock title %}
{% block content %}

{{type.title}}

<h3>{{ books.name }}</h3>
<p>{{books.description }}</p>
<div class="price_bar">
    <span class="show_price"> ￥<em>{{ books.price }}</em></span>
    <span class="show_unit">单位: {{books.unit}}</span>
</div>

{% for book in books_list %}
    <li>
        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
        <div class="price">￥{{ book.price }}</div>
    </li>
{% endfor %}
{% endblock content %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% load static %}
{% block title %} E-Book-首页 {% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block content %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 style="text-align:center"> 全部图书分类 </h1>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            <li style="float:left; margin-left:60px;"><a href=""> 首页 </a></li>
            <li style="float:left; margin-left:60px;"><a href="#model01" class="python">Python</a> </li>
            <li style="float:left; margin-left:60px;"><a href="#model02" class="javascript">Javascript</a> </li>
            <li style="float:left; margin-left:60px;"><a href="#model03" class="algorithms">Algorithms</a> </li>
            <li style="float:left; margin-left:60px;"><a href="#model04" class="machinelearning">Machinelearning</a> </li>
            <li style="float:left; margin-left:60px;"><a href="#model05" class="operationsystem">Operationsystem</a> </li>
            <li style="float:left; margin-left:60px;"><a href="#model06" class="database">Database</a> </li>
        </ul>
    </div><br/>

    <div class="list_model" style="float:left;">
        <div class="list_title clearfix">
            <h3 class="'fl" id="'model01">Python</h3>
            <div class="'subtitle fl">
                <span> | </span>
                {% for book in python_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}"> {{ book.name }} </a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr"> 查看更多 </a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static '/books/images/banner01.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in python_hot %}
                    <li>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
                        <div class="price"> ￥ {{ book.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model" >
        <div class="list_title clearfix">
            <h3 class="'fl" id="'model02">Javascript</h3>
            <div class="'subtitle fl">
                <span> | </span>
                {% for book in javascript_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}"> {{ book.name }} </a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=2 page=2 %}" class="book_more fr"> 查看更多 </a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'books/images/banner02.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in javascript_hot %}
                    <li>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
                        <div class="price"> ￥ {{ book.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
     </div><br/>

    <div class="list_model" style="float:left;">
        <div class="list_title clearfix">
            <h3 class="'fl" id="'model03"> Algorithms </h3>
            <div class="'subtitle fl">
                <span> | </span>
                {% for book in algorithms_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}"> {{ book.name }} </a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=3 page=3 %}" class="book_more fr"> 查看更多 </a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'books/images/banner03.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in algorithms_hot %}
                    <li>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
                        <div class="price"> ￥ {{ book.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="'fl" id="'model04">MachineLearning </h3>
            <div class="'subtitle fl">
                <span> | </span>
                {% for book in machinelearning_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}"> {{ book.name }} </a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=4 page=4 %}" class="book_more fr"> 查看更多 </a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'books/images/banner04.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in machinelearning_hot %}
                    <li>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
                        <div class="price"> ￥ {{ book.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div><br/><br/>

    <div class="list_model" style="float:left;">
        <div class="list_title clearfix">
            <h3 class="'fl" id="'model05">Operationsystem</h3>
            <div class="'subtitle fl">
                <span> | </span>
                {% for book in operationsystem_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}"> {{ book.name }} </a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=5 page=5 %}" class="book_more fr"> 查看更多 </a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'books/images/banner05.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in operationsystem_hot %}
                    <li>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
                        <div class="price"> ￥ {{ book.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="'fl" id="'model06">Database</h3>
            <div class="'subtitle fl">
                <span> | </span>
                {% for book in database_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}"> {{ book.name }} </a>
                {% endfor %}
            </div>
            <a href="{% url 'books:list' type_id=6 page=6 %}" class="book_more fr"> 查看更多 </a>
        </div>

        <div class="book_con clearfix">
            <div class="book_banner fl"><img src="{% static 'books/images/banner06.jpg' %}"></div>
            <ul class="book_list fl">
                {% for book in database_hot %}
                    <li>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"/></a>
                        <div class="price"> ￥ {{ book.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

books/templates/books/list.html
{% extends 'books/base.html' %}
{% load static %}
{% block title %} E-Book-商品列表 {% endblock title %}
{% block content %}
<div class="">
    <a href="{% url 'books:index' %}">全部分类 </a>
    <span> > </span>
    <a href="#">{{ type_title }}</a>
</div>
<div class="">
    <h3>新品推荐 </h3>
    <ul>
        {% for book in books_new %}
        <li>
            <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
            <h4><a href="{% url 'books:detail' books_id=book.id %}">{{book.name}}</a></h4>
            <div class="price">￥ {{ book.price }}</div>
        </li>
        {% endfor %}
    </ul>
</div>
<div>
    <div class="sort_bar">
        <a href="/list/{{type_id}}/1/" {% if sort == 'default' %} class='active' {% endif %}>默认</a>
        <a href="/list/{{type_id}}/1/?sort=price" {% if sort == 'price' %} class='active' {% endif %}>按价格</a>
     <a href="/list/{{type_id}}/1/?sort=hot" {% if sort == 'hot' %} class='active' {% endif %}>按人气</a>
    </div>

    {% for book in books_list %}
        <li>
            <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
            <h4><a href="{% url 'books:detail' books_id=book.id %}">{{book.name}}</a></h4>
            <div>
                <span class="price">￥{{ book.price }}</span>
                <span class="unit">{{ book.unit }}</span>
                <a href="#" title="加入购物车"></a>
            </div>
        </li>
    {% endfor %}

    <div class="pagination">
        {% if books_list.has_previous %}
            <a href="/list/{{type_id}}/{{ books_list.previous_page_number }}/?sort={{sort}}">上一页</a>
        {% endif %}
        {% for pindex in pages %}
            {% if pindex == books_list.number %}
                <a href="/list/{{type_id}}/{{pindex}}/?sort={{sort}}" class="active">{{pindex}}</a>
            {% else %}
                <a href="/list/{{type_id}}/{{pindex}}/?sort={{sort}}">{{pindex}}</a>
            {% endif %}
        {% endfor %}
        {% if books_list.has_next %}
            <a href="/list/{{type_id}}/{{books_list.next_page_number}}/?sort={{sort}}">下一页 </a>
        {% endif %}
    </div>
</div>
{% endblock content %}